#!/bin/bash

before() {
    echo "quirks before for zsh-theme-powerlevel10k"
    # fix build
    sed -i '/^\s.make/c\sed -i '\''s/-Werror/#-Werror/g'\'' Makefile\nmake' PKGBUILD
}

after() {
    # use this to hack dependnecies, according to the alphabet order,
    # manjaro-zsh-config build before zsh-theme-powerlevel10k, but
    # zsh-theme-powerlevel10k is of its dependnecies, this make abort,
    # so we make manjaro-zsh-config again, after zsh-theme-powerlevel10k

    # workdir: repos/zsh-theme-powerlevel10k
    sudo pacman -U ./*zst --noconfirm
    build '../manjaro-zsh-config'
    # after manjaro-zsh-config build finished, would back to repos dir
    # zsh-theme-powerlevel10k would also cd ..
    cd 'zsh-theme-powerlevel10k'
}

build() {
    cd "$1"
    prepare
    makepkg -s --noconfirm
    post
    mv ./*zst /home/nuvole/prod
    cd ..
}

prepare() {
    echo "do the prepare jobs, $(pwd)"
    # add patches for some packages
    if [ -f 'quirks' ]; then
        chmod +x quirks
        ./quirks before
    fi
}

post() {
    if [ -f 'quirks' ]; then
        ./quirks after
    fi
}

"$1"
