#!/bin/bash

before() {
    echo "quirks before for zsh-theme-powerlevel10k"
}

after() {
    # use this to hack dependnecies, according to the alphabet order,
    # manjaro-zsh-config build before zsh-theme-powerlevel10k, but
    # zsh-theme-powerlevel10k is of its dependnecies, this make abort,
    # so we make manjaro-zsh-config again, after zsh-theme-powerlevel10k

    # workdir: repos/zsh-theme-powerlevel10k
    pacman -U ./*zst --noconfirm
    build '../manjaro-zsh-config'
    # after manjaro-zsh-config build finished, would back to repos dir
    # zsh-theme-powerlevel10k would also cd ..
    cd 'zsh-theme-powerlevel10k'
}

"$1"
