#! /bin/bash

before() {
    echo "quirks before"
    curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | gpg --import -
}

after() {
    echo "quirks after"
    for ((i = 1; i <= 5; i++))
    do
        if [ ! -f ./*zst ]; then
            makepkg -s --noconfirm
        fi
    done
}

"$1"
