#! /bin/bash

before() {
    echo "quirks before"
    cmd=$(cat PKGBUILD | sed -n 's/^#\s\(curl.*\)/\1/p')
    eval $cmd
}

after() {
    echo "quirks after"
    for ((i = 1; i <= 5; i++))
    do
        if [ ! -f ./*.pkg.tar.* ]; then
            makepkg -s --noconfirm
        fi
    done
}

"$1"
