#!/bin/bash

before() {
    echo "quirks before for ttf-meslo-nerd-font-powerlevel10k"
}

after() {
    echo "quirks after for ttf-meslo-nerd-font-powerlevel10k"
    # as a build dependency
    sudo pacman -U ./*zst --noconfirm
}

"$1"
