name: arch_aarch64_pack

on:
  schedule:
    - cron: '0 21 * * *' # everyday 9:00 pm (UTC) / 5:00 am (GTM+8)
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update
      run: |
        ${{ github.workspace }}/utils/query_update.sh aarch64
      env:
        GPG_SIGNING_KEY_ARCH: ${{ secrets.GPG_SIGNING_KEY_ARCH }}
        AUR_KEY: ${{ secrets.AUR_KEY }}

    - name: Push changes
      run: |
        git push -u origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ github.workspace }}/builddir/root.aarch64/home/nuvole/prod/*
        tag_name: aarch64-packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
