name: arch_package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y arch-install-scripts zstd wget
    - name: curl srcipt and config
      run: |
        wget http://mirror.rackspace.com/archlinux/iso/latest/archlinux-bootstrap-x86_64.tar.zst
        tar xf ./archlinux-bootstrap-x86_64.tar.zst --numeric-owner
        echo 'Server = http://mirror.rackspace.com/archlinux/$repo/os/$arch' >> ./root.x86_64/etc/pacman.d/mirrorlist
        cat ./root.x86_64/etc/pacman.d/mirrorlist | grep -Ei '^Server'
        echo 'ParallelDownloads = 4' >> ./root.x86_64/etc/pacman.conf
        sudo mount --bind ./root.x86_64/ ./root.x86_64/
        arch-chroot ./root.x86_64/ sh -c 'pacman-key --init && pacman-key --populate'
        arch-chroot ./root.x86_64/ pacman -S base-devel git wget --noconfirm
        arch-chroot ./root.x86_64/ sh -c 'cd /root && git clone https://gitlab.archlinux.org/archlinux/packaging/packages/linux-lts.git'
        arch-chroot ./root.x86_64/ sh -c 'gpg --recv-keys ABAF11C65A2970B130ABE3C479BE3E4300411886 && gpg --recv-keys 647F28654894E3BD457199BE38DBBDC86092693E'
        arch-chroot ./root.x86_64/ sh -c 'cd ./root.x86_64/root/linux-lts && wget https://ftp.nuvole.eu.org/linux-ego/0099-fix-pnp.patch && makepkg -si'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-lts
        path: |
          root.x86_64/root/linux-lts/linux-lts*.zst
