name: arch_package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y arch-install-scripts zstd curl
    - name: curl srcipt and config
      run: |
        curl http://mirror.rackspace.com/archlinux/iso/latest/archlinux-bootstrap-x86_64.tar.zst -o archlinux-bootstrap-x86_64.tar.zst
        tar xf ./archlinux-bootstrap-x86_64.tar.zst --numeric-owner
        echo 'Server = http://mirror.rackspace.com/archlinux/$repo/os/$arch' >> ./root.x86_64/etc/pacman.d/mirrorlist
        sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 4/' ./root.x86_64/etc/pacman.conf
        cat ./root.x86_64/etc/pacman.d/mirrorlist | grep -Ei '^Server'
        cat ./root.x86_64/etc/pacman.conf | grep 'ParallelDownloads'
        sudo chown root:root -R ./root.x86_64
        sudo mount --bind ./root.x86_64/ ./root.x86_64/
        sudo arch-chroot ./root.x86_64/ sh -c 'pacman-key --init && pacman-key --populate && pacman -Syu --noconfirm'
        sudo arch-chroot ./root.x86_64/ pacman -S base-devel git wget --noconfirm
        sudo arch-chroot ./root.x86_64/ sh -c 'useradd -m -s /bin/bash builduser && cd /home/builduser && su - builduser -c "git clone https://gitlab.archlinux.org/archlinux/packaging/packages/linux-lts.git"'
        sudo arch-chroot ./root.x86_64/ sh -c 'su - builduser -c "cd linux-lts/keys/pgp && gpg --import 647F28654894E3BD457199BE38DBBDC86092693E.asc && gpg --import ABAF11C65A2970B130ABE3C479BE3E4300411886.asc"'
        sudo arch-chroot ./root.x86_64/ sh -c 'su - builduser -c "cd linux-lts && wget https://ftp.nuvole.eu.org/0099-fix-pnp.patch && makepkg -si"'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-lts
        path: |
          root.x86_64/root/linux-lts/linux-lts*.zst
